import 'dart:async';

import 'package:dio/dio.dart';
import 'package:pixes/appdata.dart';
import 'package:pixes/foundation/history.dart';
import 'package:pixes/foundation/log.dart';
import 'package:pixes/network/models.dart';
import 'package:uuid/uuid.dart';

/*
-- Run this SQL in your Supabase SQL Editor:
create table if not exists sync_devices (
  device_id text primary key,
  device_name text not null default '',
  last_sync_at timestamp with time zone default timezone('utc'::text, now()),
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);
create table if not exists sync_settings (
  id bigint generated by default as identity primary key,
  data jsonb,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null
);
create table if not exists sync_search_history (
  id bigint generated by default as identity primary key,
  keyword text not null,
  search_type int not null,
  data jsonb,
  unique(keyword, search_type),
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);
create table if not exists sync_browsing_history (
  id bigint generated by default as identity primary key,
  illust_id bigint not null,
  data jsonb,
  unique(illust_id),
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);
-- If you get 401 errors, disable RLS on these tables:
alter table sync_devices disable row level security;
alter table sync_settings disable row level security;
alter table sync_search_history disable row level security;
alter table sync_browsing_history disable row level security;
*/

class SyncService {
  static SyncService? _instance;
  factory SyncService() => _instance ??= SyncService._();
  SyncService._();

  Dio? _dio;
  Timer? _debounceTimer;
  int? lastStatusCode;
  bool _stopped = false;
  bool _pulling = false;

  String? get _url => appdata.settings["syncUrl"] as String?;
  String? get _key => appdata.settings["syncKey"] as String?;

  bool get enabled {
    if (appdata.settings["syncEnabled"] != true) return false;
    final url = _url;
    final key = _key;
    return url != null && url.isNotEmpty && key != null && key.isNotEmpty;
  }

  bool get syncSettingsEnabled =>
      appdata.settings["syncSettingsEnabled"] != false;

  String? get projectId {
    final url = _url;
    if (url == null || url.isEmpty) return null;
    final u = url.replaceFirst('https://', '').replaceFirst('http://', '');
    final dot = u.indexOf('.');
    if (dot <= 0) return null;
    return u.substring(0, dot);
  }

  bool get needsSetup => lastStatusCode == 401 || lastStatusCode == 403;
  bool get stopped => _stopped;

  String get _deviceId {
    var id = appdata.settings["syncDeviceId"] as String?;
    if (id == null || id.isEmpty) {
      id = const Uuid().v4();
      appdata.settings["syncDeviceId"] = id;
      appdata.writeSettings();
    }
    return id;
  }

  String get deviceName =>
      appdata.settings["syncDeviceName"] as String? ?? "";

  void resetDeviceId() {
    appdata.settings["syncDeviceId"] = const Uuid().v4();
    appdata.writeSettings();
  }

  bool _ensureDio() {
    if (!enabled || _stopped) return false;
    if (_dio != null) return true;
    _dio = Dio(BaseOptions(
      baseUrl: "${_url!}/rest/v1/",
      headers: {
        'apikey': _key!,
        'Authorization': 'Bearer ${_key!}',
        'Content-Type': 'application/json',
        'Accept': 'application/json',
      },
      validateStatus: (_) => true,
    ));
    return true;
  }

  void reconfigure() {
    _dio = null;
    _debounceTimer?.cancel();
    _debounceTimer = null;
    _stopped = false;
  }

  void init() {
    if (!enabled) return;
    if (!_ensureDio()) return;
    _pullAll();
  }

  void notifyChange() {
    if (!enabled) return;
    if (_stopped) return;
    if (_pulling) return;
    _debounceTimer?.cancel();
    _debounceTimer = Timer(const Duration(seconds: 2), _pushAll);
  }

  bool _ok(Response r) {
    lastStatusCode = r.statusCode;
    if (r.statusCode == 401 || r.statusCode == 403) {
      _stopped = true;
      Log.error("Sync", "Stopped due to HTTP ${r.statusCode}");
    }
    return r.statusCode != null && r.statusCode! >= 200 && r.statusCode! < 300;
  }

  Future<void> _pullAll() async {
    if (!_ensureDio()) return;
    _pulling = true;
    try {
      final futures = <Future<void>>[];
      futures.add(_pullSearchHistory());
      futures.add(_pullBrowsingHistory());
      if (syncSettingsEnabled) futures.add(_pullSettings());
      await Future.wait(futures);
      await _upsertDevice();
    } finally {
      _pulling = false;
    }
  }

  Future<void> _pushAll() async {
    if (!_ensureDio()) return;
    final futures = <Future<void>>[];
    futures.add(_pushSearchHistory());
    futures.add(_pushBrowsingHistory());
    if (syncSettingsEnabled) futures.add(_pushSettings());
    await Future.wait(futures);
    await _upsertDevice();
  }

  Future<String?> syncNow() async {
    if (!_ensureDio()) return "Sync not configured";
    _stopped = false;
    await _pushAll();
    await _pullAll();
    return null;
  }

  Future<int?> checkConnection() async {
    if (!_ensureDio()) {
      _stopped = false;
      return null;
    }
    _stopped = false;
    try {
      final res = await _dio!.get('/sync_devices?select=device_id&limit=1');
      lastStatusCode = res.statusCode;
      return res.statusCode;
    } catch (_) {
      return null;
    }
  }

  Future<void> _pullSettings() async {
    if (!syncSettingsEnabled || _stopped) return;
    final res = await _dio!.get('/sync_settings?select=data,updated_at&id=eq.1');
    if (!_ok(res) || res.data == null || (res.data as List).isEmpty) return;
    final row = (res.data as List)[0] as Map<String, dynamic>;
    final remoteData = row['data'] as Map<String, dynamic>;
    final remoteTime = DateTime.parse(row['updated_at'] as String);
    final localTimeStr = appdata.settings["syncSettingsUpdatedAt"] as String?;
    final localTime = localTimeStr != null ? DateTime.tryParse(localTimeStr) : null;
    if (localTime == null || remoteTime.isAfter(localTime)) {
      for (var key in remoteData.keys) {
        appdata.settings[key] = remoteData[key];
      }
      appdata.settings["syncSettingsUpdatedAt"] = remoteTime.toIso8601String();
      appdata.writeSettings();
    }
  }

  Future<void> _pushSettings() async {
    if (!syncSettingsEnabled || _stopped) return;
    final data = Map<String, dynamic>.from(appdata.settings);
    data.remove("syncKey");
    data.remove("syncUrl");
    data.remove("syncDeviceId");
    data.remove("syncDeviceName");
    data.remove("syncSettingsUpdatedAt");
    data.remove("syncEnabled");
    data.remove("syncSettingsEnabled");
    final now = DateTime.now().toIso8601String();
    appdata.settings["syncSettingsUpdatedAt"] = now;
    final res = await _dio!.post('/sync_settings', data: {
      'id': 1,
      'data': data,
      'updated_at': now,
    }, options: Options(headers: {'Prefer': 'resolution=merge-duplicates'}));
    if (!_ok(res)) {
      Log.error("Sync", "Push settings failed: ${res.statusCode} ${res.statusMessage}");
    }
  }

  Future<void> _pullSearchHistory() async {
    if (_stopped) return;
    final res = await _dio!.get('/sync_search_history?select=data,keyword,search_type,updated_at');
    if (!_ok(res) || res.data == null) return;
    final remote = (res.data as List).map((e) {
      final row = e as Map<String, dynamic>;
      return (
        entry: SearchHistoryEntry.fromJson(row['data'] as Map<String, dynamic>),
        updatedAt: row['updated_at'] as String?
      );
    }).toList();
    final local = appdata.getSearchHistory();
    final seen = <String>{};
    final merged = <SearchHistoryEntry>[];
    for (var e in local) {
      seen.add("${e.keyword}:${e.searchType}");
      merged.add(e);
    }
    for (var r in remote) {
      final key = "${r.entry.keyword}:${r.entry.searchType}";
      if (!seen.contains(key)) {
        seen.add(key);
        merged.add(r.entry);
      }
    }
    appdata.importSearchHistory(merged);
  }

  Future<void> _pushSearchHistory() async {
    if (_stopped) return;
    final local = appdata.getSearchHistory();
    final now = DateTime.now().toIso8601String();
    for (var entry in local) {
      final res = await _dio!.post('/sync_search_history?on_conflict=keyword,search_type', data: {
        'keyword': entry.keyword,
        'search_type': entry.searchType,
        'data': entry.toJson(),
        'updated_at': now,
      }, options: Options(headers: {'Prefer': 'resolution=merge-duplicates'}));
      if (!_ok(res)) {
        Log.error("Sync", "Push search history failed: ${res.statusCode}");
        continue;
      }
    }
  }

  Future<void> _pullBrowsingHistory() async {
    if (_stopped) return;
    final res = await _dio!.get('/sync_browsing_history?select=data,illust_id,updated_at');
    if (!_ok(res) || res.data == null) return;
    final remote = (res.data as List).map((e) {
      final d = (e as Map<String, dynamic>)['data'] as Map<String, dynamic>;
      return IllustHistory(
        d['id'] as int,
        d['imgPath'] as String,
        DateTime.parse(d['time'] as String),
        d['imageCount'] as int,
        (d['isR18'] as num) == 1,
        (d['isR18G'] as num) == 1,
        (d['isAi'] as num) == 1,
        (d['isGif'] as num) == 1,
        d['width'] as int,
        d['height'] as int,
      );
    }).toList();
    final local = HistoryManager().getAll();
    final map = <int, IllustHistory>{};
    for (var e in local) { map[e.id] = e; }
    for (var e in remote) { map[e.id] = e; }
    HistoryManager().importAll(map.values.toList());
  }

  Future<void> _pushBrowsingHistory() async {
    if (_stopped) return;
    final local = HistoryManager().getAll();
    final now = DateTime.now().toIso8601String();
    for (var h in local) {
      final res = await _dio!.post('/sync_browsing_history?on_conflict=illust_id', data: {
        'illust_id': h.id,
        'data': {
          'id': h.id,
          'imgPath': h.imgPath,
          'time': h.time.toIso8601String(),
          'imageCount': h.imageCount,
          'isR18': h.isR18 ? 1 : 0,
          'isR18G': h.isR18G ? 1 : 0,
          'isAi': h.isAi ? 1 : 0,
          'isGif': h.isGif ? 1 : 0,
          'width': h.width,
          'height': h.height,
        },
        'updated_at': now,
      }, options: Options(headers: {'Prefer': 'resolution=merge-duplicates'}));
      if (!_ok(res)) {
        Log.error("Sync", "Push browsing history failed: ${res.statusCode}");
        continue;
      }
    }
  }

  Future<void> _upsertDevice() async {
    if (_stopped) return;
    final now = DateTime.now().toIso8601String();
    final res = await _dio!.post('/sync_devices', data: {
      'device_id': _deviceId,
      'device_name': deviceName,
      'last_sync_at': now,
    }, options: Options(headers: {'Prefer': 'resolution=merge-duplicates'}));
    if (!_ok(res)) {
      Log.error("Sync", "Upsert device failed: ${res.statusCode}");
    }
  }

  Future<List<Map<String, dynamic>>> getDevices() async {
    if (!_ensureDio()) return [];
    try {
      final res = await _dio!.get(
        '/sync_devices',
        queryParameters: {
          'select': 'device_id,device_name,last_sync_at,inserted_at',
          'order': 'last_sync_at.desc',
        },
      );
      lastStatusCode = res.statusCode;
      if (!_ok(res) || res.data == null) return [];
      return (res.data as List).cast<Map<String, dynamic>>();
    } catch (_) {
      return [];
    }
  }

  Future<Map<String, int>> getLocalCounts() async {
    return {
      'searchHistory': appdata.getSearchHistory().length,
      'browsingHistory': HistoryManager().length,
    };
  }

  Future<bool> clearRemoteData() async {
    if (!_ensureDio()) return false;
    final results = await Future.wait([
      _dio!.delete('/sync_search_history'),
      _dio!.delete('/sync_browsing_history'),
      _dio!.delete('/sync_settings?id=eq.1'),
      _dio!.delete('/sync_devices?device_id=neq.$_deviceId'),
    ]);
    return results.every((r) => _ok(r));
  }
}

final syncService = SyncService();
